import { Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import Incident from '../models/Incident.js';
import RCA from '../models/RCA.js';
import { logActivity } from '../utils/activityLogger.js';

export const generateReport = async (req: Request, res: Response): Promise<any> => {
    try {
        const { report_type, incident_id, date_range } = req.body;
        
        // Ensure user is authorized
        const user = (req as any).user;
        if (!user || user.role !== 'admin') {
            return res.status(403).json({ message: 'Access denied: Only Admins can generate reports' });
        }

        if (report_type === 'incident' && !incident_id) {
            return res.status(400).json({ message: 'incident_id is required for incident reports' });
        }

        const doc = new PDFDocument({ margin: 50 });
        
        // Setup response headers for PDF download
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=OpsPulse_${report_type}_report.pdf`);
        
        doc.pipe(res);
        
        // Header
        doc.fontSize(24).font('Helvetica-Bold').fillColor('#4f46e5').text('OpsPulse Operational Dashboard', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(12).font('Helvetica').fillColor('#475569').text(`Report Generated On: ${new Date().toLocaleString()}`, { align: 'center' });
        doc.text(`Generated By: ${user.name} (${user.email})`, { align: 'center' });
        doc.moveDown(2);

        if (report_type === 'incident') {
            const incident = await Incident.findById(incident_id).populate('assignedTo', 'name email');
            if (!incident) {
                // Return gracefully via PDF output if we already piped or status if headers not sent
                // Since pipe happens before this, it's safer to fetch data *before* pipe
            }
            
            const rca = await RCA.findOne({ incident_id });

            doc.fillColor('#0f172a').fontSize(18).font('Helvetica-Bold').text(`Incident Report: ${incident?.title || 'Unknown'}`);
            doc.moveDown();
            
            doc.fontSize(12).font('Helvetica-Bold').fillColor('#334155').text('Incident Details');
            doc.font('Helvetica').fillColor('#000000').text(`ID: ${incident?._id}`);
            doc.text(`Status: ${incident?.status}`);
            doc.text(`Severity: ${incident?.severity}`);
            doc.text(`Created At: ${incident?.timestamp}`);
            doc.text(`Assigned To: ${incident?.assignedTo ? (incident.assignedTo as any).name : 'Unassigned'}`);
            doc.moveDown();
            
            doc.font('Helvetica-Bold').text('Description / Root Cause Notes');
            doc.font('Helvetica').text(incident?.rootCause || 'N/A');
            doc.moveDown();
            
            doc.font('Helvetica-Bold').text('Affected Services');
            doc.font('Helvetica').text((incident?.affectedServices || []).join(', ') || 'None');
            doc.moveDown();
            
            doc.font('Helvetica-Bold').text('Resolution Steps');
            if (incident?.resolutionSteps && incident.resolutionSteps.length > 0) {
                incident.resolutionSteps.forEach((step: string, idx: number) => {
                    doc.font('Helvetica').text(`${idx + 1}. ${step}`);
                });
            } else {
                doc.font('Helvetica-Oblique').text('No resolution steps provided.');
            }
            doc.moveDown(2);
            
            if (rca) {
                doc.fontSize(16).font('Helvetica-Bold').fillColor('#10b981').text('Root Cause Analysis (RCA)');
                doc.moveDown();
                doc.fontSize(12).font('Helvetica-Bold').fillColor('#000000').text(`Category: ${rca.category} | Status: ${rca.status}`);
                doc.moveDown(0.5);
                doc.font('Helvetica-Bold').text('Summary:');
                doc.font('Helvetica').text(rca.summary);
                doc.moveDown(0.5);
                doc.font('Helvetica-Bold').text('Detailed Analysis:');
                doc.font('Helvetica').text(rca.detailed_analysis);
                doc.moveDown(0.5);
                doc.font('Helvetica-Bold').text('Preventive Measures:');
                doc.font('Helvetica').text(rca.preventive_measures);
            } else {
                doc.font('Helvetica-Oblique').text('No Root Cause Analysis (RCA) document is associated with this incident.');
            }

            await logActivity(`Generated Incident Report for ${incident?.title}`, user._id);
            
        } else if (report_type === 'weekly') {
            doc.fillColor('#0f172a').fontSize(18).font('Helvetica-Bold').text('Weekly Operational Summary Report');
            doc.moveDown();
            
            // Calculate last 7 days range
            const end = new Date();
            const start = new Date();
            start.setDate(start.getDate() - 7);
            
            doc.fontSize(12).font('Helvetica').text(`Reporting Period: ${start.toLocaleDateString()} to ${end.toLocaleDateString()}`);
            doc.moveDown(2);
            
            // Fetch stats
            const totalIncidents = await Incident.countDocuments({ timestamp: { $gte: start, $lte: end } });
            const resolvedIncidents = await Incident.countDocuments({ status: 'resolved', timestamp: { $gte: start, $lte: end } });
            
            doc.font('Helvetica-Bold').text('Global Incident Metrics');
            doc.font('Helvetica').text(`Total Supported Incidents: ${totalIncidents}`);
            doc.text(`Resolved Incidents: ${resolvedIncidents}`);
            doc.text(`Resolution Rate: ${totalIncidents > 0 ? Math.round((resolvedIncidents / totalIncidents) * 100) : 0}%`);
            doc.moveDown();
            
            // RCA Category Breakdown
            const rcaStats = await RCA.aggregate([
                { $match: { createdAt: { $gte: start, $lte: end }, status: 'Approved' } },
                { $group: { _id: '$category', count: { $sum: 1 } } }
            ]);
            
            doc.font('Helvetica-Bold').text('RCA Breakdown by Category (Approved RCAs)');
            if (rcaStats.length > 0) {
                rcaStats.forEach((stat: any) => {
                    doc.font('Helvetica').text(`- ${stat._id}: ${stat.count}`);
                });
            } else {
                doc.font('Helvetica-Oblique').text('No approved RCAs found in this reporting period.');
            }
            doc.moveDown(2);

            doc.font('Helvetica-Oblique').fillColor('#64748b').text('Note: This weekly report summarizes the high-level platform stability metrics.');
            
            await logActivity(`Generated Weekly Summary Report`, user._id);
        } else {
            doc.font('Helvetica-Bold').fillColor('red').text('INVALID REPORT TYPE');
        }
        
        doc.end();
            
    } catch (error) {
        console.error('Error generating report:', error);
        if (!res.headersSent) {
            res.status(500).json({ message: 'Error generating report.' });
        }
    }
};
